site_name: Arduitronicshub
nav:
    - Home: index.md
    - About: about.md
theme: readthedocs

extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.6.0/clipboard.min.js
  - extra.js

markdown_extensions:
  - footnotes
  - codehilite:
      linenums: true
